name: CI

on:
  push:
    branches: [main]
    tags: [v*]
    paths-ignore:
      - 'README.md'

jobs:
  build-gh-pages:
    name: Build GH Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ./src
        run: npm install

      - name: Build Demo
        working-directory: ./src
        run: node pages.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: src/gh-pages